# This file is generated by opta, do not modify it manually.
provider "aws" {
  region              = "us-east-2"
  allowed_account_ids = ["111111111"]

  default_tags {
    tags = {
      environment_name = "production"
      region           = "production"
      layer_name       = "production-production"
    }
  }
}